### ISSUE TITLE
SortMeRNA v4.3.2: Segmentation fault with multiple threads and "--other" argument

### ISSUE THREAD

**Issue by tbigot** [biocore/sortmerna#288]
Using SortMeRNA v4.3.2, I frequently have segmentation faults, depending on the sample analyzed. Sometimes reducing the number of thread make it work, sometimes it doesn’t. In the following trace, I used 90 threads to get the result faster, but it segfaults the same way with only 10 threads.

[sortmerna_segfault_trace.log](https://github.com/biocore/sortmerna/files/6312940/sortmerna_segfault_trace.log)

Edit: the launching command is in the log, but I paste it here to be more convenient:

```sh
sortmerna --dbg-level 2 --workdir ./sortmerna -v --threads 90 --ref /pasteur/zeus/projets/p02/stella-run/microseek/database/rRNA-sortmerna/smr_v4.3_default_db.fasta --reads step/trimmed_reads/singleR1_trimmed.fastq --num_alignments 1 --fastx --aligned aligned --other other
```

**Comment by tbigot** [comment]
Bug reproduction:
Segfaults at 100k reads but not 10k (80 threads)
segfaults at 1000k reads but not 100k (40 threads)
segfaults using `--other` (with or without argument) but no segfault without it.

**Comment by tbigot** [comment]
v4.3.1 seems to have introduced the bug, since v4.2.0 works fine.

**Comment by biocodz** [comment]
The log shows the error happens while generating the reports. The alignment was done OK. At least this is a good news.
Does the `WORKDIR/out/aligned.log` file looks OK?
Do I understand correctly that using either `-other` or `-other other` makes no difference i.e. both result in segfault?
I'll try to reproduce the bug.

**Comment by tbigot** [comment]
Using either `-other` or `-other other` leads to segfaults.
I had no chance to see if the output files were ok, since this job is included in a pipeline and if it fails, the temporary directory in which the jobs occurs is deleted. Running it manually, I’m not sure if other was output properly.

**Comment by biocodz** [comment]
This one could be tough to reproduce. I did many tests in different environments on both gzipped and flat files, and all kinds of option combinations, and have never seen this problem. But of course I only test sortmerna, and no pipelines involved i.e the setup is much more straightforward.  The fact the error occurs intermittently makes it even more elusive and hard to pin down (actually a developer nightmare:-). 
Currently I'm preparing the tests to run on HPC, so may be a more complex setup will reveal this problem.

If you could test a subset of your data e.g. 1M reads that causes this problem, and pass that to me, it would be a tremendous help.

**Comment by tbigot** [comment]
I understand that, and as a developer too, I strongly relate. ;-)

I tried to compile sortmerna with debug symbols, but the dependencies make it hard to compile without your `build.py` script. And this script expects a machine with a debian-like distro and/or root privileges and/or recent GCC that I do not have. Maybe you could provide me with a pre-compiled debug release to me so that I can execute at my side and give you a proper debug trace?

On the other hand, as soon as I can take time to provide you with non-human and non-“embargoed” files, I’ll do it!

**Comment by biocodz** [comment]
Please, find the requested [sortmerna-4.3.2-Linux-debug.tar.gz](https://github.com/biocore/sortmerna/releases/download/v4.3.2/sortmerna-4.3.2-Linux-debug.tar.gz). Built from the current master head, so a bit ahead of 4.3.2. It cleans a small part of a bunch of compilation warnings shown during the build. One of those warnings could be responsible for the bug due e.g. an integer overflow. We'll see. 
Thanks for the input, and the willingness to help:-)

**Comment by tbigot** [comment]
I’ve just tried the version in your archive (the debug one) and cannot reproduce the segmentation fault.

I hope it’s not just the fact that it’s compiled in debug mode (I’ve already seen that :-D )

**Comment by biocodz** [comment]
Yeah, optimized code can behave quite differently.
From your trace I can see the error happened right after all the report processing threads have started, so I'll try to analyze the code and to add some error handling. Also I'll finish cleaning-up the warnings and make a new release soon. Hopefully those simple things will rectify this problem.

**Comment by tbigot** [comment]
I manage to get a segfault, but it is very strange:
1st execution: no segfault
2nd execution, after a `rm -fr sortmerna/kvdb`: segfault
3rd execution and subsequent ones, after a `rm -fr sortmerna/kvdb` each time: no segfault

Please find the dumped core here http://dl.pasteur.fr/fop/Onjar7KI/core.3415372.xz

**Comment by biocodz** [comment]
Got the file. I'll work on it. Thanks!

**Comment by biocodz** [comment]
The dump unfortunately didn't help much. The trace ends in a library function, so it's not clear where in the application code the bug is. Not able even to figure out whether SMR or RocksDB is responsible. I'm more inclined to think it's SMR but cannot discard other possibilities.
I re-built the [debug binaries](https://github.com/biocore/sortmerna/releases/download/v4.3.2/sortmerna-4.3.7adb50-Linux.tar.gz) using a newer version of GCC. Hopefully it would provide a better trace. The build also fixes some compiler warnings.

**Comment by tbigot** [comment]
Thanks! This time the segfault occurred on the first run.
http://dl.pasteur.fr/fop/o6Pal8Q7/core.4071754.xz

**Comment by biocodz** [comment]
great, thanks! What's the `uname -a` on your system?

**Comment by tbigot** [comment]
`Linux maestro-submit 4.18.0-240.10.1.el8_3.x86_64 #1 SMP Mon Jan 18 17:05:51 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by biocodz** [comment]
what's the output of `hostnamectl`?
I suspect the fact the binaries were built on a Debian family system has to do with your problem.

**Comment by tbigot** [comment]
```
   Static hostname: maestro-submit
         Icon name: computer-server
           Chassis: server
        Machine ID: ed81c95e9bef4f70ba65aa858f04b2d4
           Boot ID: bcaab732d6c5478992d05ddf305c0b7d
  Operating System: CentOS Linux 8
       CPE OS Name: cpe:/o:centos:centos:8
            Kernel: Linux 4.18.0-240.10.1.el8_3.x86_64
      Architecture: x86-64
```

Thanks for the binaries, I’ll try that.

**Comment by tbigot** [comment]
I confirm `--task 2` is sufficient to trigger segmentation fault.

**Comment by tbigot** [comment]
Unfortunately, the segfault still occurs with the Centos version. Here is the core dump:
http://dl.pasteur.fr/fop/bPgLWZln/core.1320480.xz

Good luck!

**Comment by biocodz** [comment]
I didn't hold my breath anyway:-)
Good news however, this trace is Much better, and it shows exactly where the error occurs, which is on banal writing to the report file.  Should be easy to figure out.

**Comment by biocodz** [comment]
Please, try the new pre-release [v4.3.3-pre](https://github.com/biocore/sortmerna/releases/tag/v4.3.3-pre). It introduces quite a bit of fixes, and hopefully one of them will rectify this problem.

**Comment by biocodz** [comment]
fixed in [v4.3.3](https://github.com/biocore/sortmerna/releases/tag/v4.3.3)

**Comment by AryLech** [comment]
Hi!

I have the same problem usinig SortMeRNA v4.3.2. I tried to solve using v4.3.3 and v4.3.4 and reducing the number of threads in a half but the problem persists. It only appears in unpaired reads. I managed to run the program by adding -paired_out, but the warning is still in some samples.

I run the next command:

sortmerna-4.3.2-Linux/bin/sortmerna -ref sortmerna-4.3.2-Linux/database/smr_v4.3_default_db.fasta -reads unpaired_DR04_R1_2.fastq.gz -fastx -other unpaired_DR04_R1_non-ribosomal -aligned unpaired_DR04_R1_2_ribosomal --workdir Sortmerna_Filter_cdefault/2_MT/DR04_R1/ --SortMeRNA_Filter_cdefault/idx/ --threads 16

I don´t know what else to do. And and tried with v4.2.0 and the warmining dosen´t appear but it still in the other versions.

**Comment by biocodz** [comment]
Hi. 
Could you please provide the [execution-trace](https://github.com/biocore/sortmerna#execution-trace)
Please, use the v4.3.4. 4.3.2 has a major problem using many threads (albeit whith the number more than 16)

**Comment by AryLech** [comment]
Hi, 

**using v4.3.2 with threads 16**

arely@proyecto-h:/mnt/9C908FFC908FDB62/Arely/Metatranscriptoma_BP8/Sortmerna_Filter_cdefault/2_MT_BP8$ /home/proyectoh/Programas/sortmerna-4.3.2-Linux/bin/sortmerna -ref /home/proyectoh/Programas/sortmerna-4.3.2-Linux/database/smr_v4.3_default_db.fasta -reads /mnt/9C908FFC908FDB62/Arely/Metatranscriptoma_BP8/Trimmomatic_Filter_cutdefault/unpaired_DR04_R1_2.fastq.gz -fastx -other unpaired_DR04_3d_R1_non-ribosomal_2 -aligned unpaired_DR04_3d_R1_2_ribosomal --workdir /mnt/9C908FFC908FDB62/Arely/Metatranscriptoma_BP8/Sortmerna_Filter_cdefault/2_MT_BP8/DR04_R1/ --idx-dir /mnt/9C908FFC908FDB62/Arely/MT_BP8/SortMeRNA_Filter/idx/ --threads 16
[process:1372] === Options processing starts ... ===
Found value: /home/proyectoh/Programas/sortmerna-4.3.2-Linux/bin/sortmerna
Found flag: -ref
Found value: /home/proyectoh/Programas/sortmerna-4.3.2-Linux/database/smr_v4.3_default_db.fasta of previous flag: -ref
Found flag: -reads
Found value: /mnt/9C908FFC908FDB62/Arely/Metatranscriptoma_BP8/Trimmomatic_Filter_cutdefault/unpaired_DR04_R1_2.fastq.gz of previous flag: -reads
Found flag: -fastx
Previous flag: -fastx is Boolean. Setting to True
Found flag: -other
Found value: unpaired_DR04_3d_R1_non-ribosomal_2 of previous flag: -other
Found flag: -aligned
Found value: unpaired_DR04_3d_R1_2_ribosomal of previous flag: -aligned
Found flag: --workdir
Found value: /mnt/9C908FFC908FDB62/Arely/Metatranscriptoma_BP8/Sortmerna_Filter_cdefault/2_MT_BP8/DR04_R1/ of previous flag: --workdir
Found flag: --idx-dir
Found value: /mnt/9C908FFC908FDB62/Arely/MT_BP8/SortMeRNA_Filter/idx/ of previous flag: --idx-dir
Found flag: --threads
Found value: 16 of previous flag: --threads
[opt_workdir:990] Using WORKDIR: "/mnt/9C908FFC908FDB62/Arely/Metatranscriptoma_BP8/Sortmerna_Filter_cdefault/2_MT_BP8/DR04_R1/" as specified
[process:1456] Processing option: aligned with value: unpaired_DR04_3d_R1_2_ribosomal
[process:1456] Processing option: fastx with value: 
[process:1456] Processing option: idx-dir with value: /mnt/9C908FFC908FDB62/Arely/MT_BP8/SortMeRNA_Filter/idx/
[opt_idxdir:1014] Using IDX dir: ["/mnt/9C908FFC908FDB62/Arely/MT_BP8/SortMeRNA_Filter/idx/" as specified
[process:1456] Processing option: other with value: unpaired_DR04_3d_R1_non-ribosomal_2
[process:1456] Processing option: reads with value: /mnt/9C908FFC908FDB62/Arely/Metatranscriptoma_BP8/Trimmomatic_Filter_cutdefault/unpaired_DR04_R1_2.fastq.gz
[opt_reads:97] Processing reads file [1] out of total [1] files
[process:1456] Processing option: ref with value: /home/proyectoh/Programas/sortmerna-4.3.2-Linux/database/smr_v4.3_default_db.fasta
[opt_ref:157] Processing reference [1] out of total [1] references
[opt_ref:205] File "/home/proyectoh/Programas/sortmerna-4.3.2-Linux/database/smr_v4.3_default_db.fasta" exists and is readable
[process:1456] Processing option: threads with value: 16
[process:1476] === Options processing done ===
[process:1477] Alignment type: [best:1 num_alignments:1 min_lis:2 seeds:2]
[validate_kvdbdir:1223] Key-value DB location "/mnt/9C908FFC908FDB62/Arely/Metatranscriptoma_BP8/Sortmerna_Filter_cdefault/2_MT_BP8/DR04_R1/kvdb"
[validate_kvdbdir:1259] Creating KVDB directory: "/mnt/9C908FFC908FDB62/Arely/Metatranscriptoma_BP8/Sortmerna_Filter_cdefault/2_MT_BP8/DR04_R1/kvdb"
[validate_idxdir:1189] Using index directory: "/mnt/9C908FFC908FDB62/Arely/MT_BP8/SortMeRNA_Filter/idx/"
[validate_idxdir:1205] IDX directory: "/mnt/9C908FFC908FDB62/Arely/MT_BP8/SortMeRNA_Filter/idx/" exists and is not empty
[validate_readb_dir:1281] Using split reads directory : "/mnt/9C908FFC908FDB62/Arely/Metatranscriptoma_BP8/Sortmerna_Filter_cdefault/2_MT_BP8/DR04_R1/readb"
[validate_readb_dir:1289] Created split reads directory - OK
[main:62] Running command:
/home/proyectoh/Programas/sortmerna-4.3.2-Linux/bin/sortmerna -ref /home/proyectoh/Programas/sortmerna-4.3.2-Linux/database/smr_v4.3_default_db.fasta -reads /mnt/9C908FFC908FDB62/Arely/Metatranscriptoma_BP8/Trimmomatic_Filter_cutdefault/unpaired_DR04_R1_2.fastq.gz -fastx -other unpaired_DR04_3d_R1_non-ribosomal_2 -aligned unpaired_DR04_3d_R1_2_ribosomal --workdir /mnt/9C908FFC908FDB62/Arely/Metatranscriptoma_BP8/Sortmerna_Filter_cdefault/2_MT_BP8/DR04_R1/ --idx-dir /mnt/9C908FFC908FDB62/Arely/MT_BP8/SortMeRNA_Filter/idx/ --threads 16 
[Index:102] Found 4 non-empty index files. Skipping indexing.
[init:108] Readfeed init started
[define_format:885] file: "/mnt/9C908FFC908FDB62/Arely/Metatranscriptoma_BP8/Trimmomatic_Filter_cutdefault/unpaired_DR04_R1_2.fastq.gz" is FASTQ gzipped
[count_reads:919] started count  ...   
[next:311] EOF FWD reached. Total reads: 3116831
[count_reads:949] done count. Elapsed time: 9.0157 sec. Total reads: 3116831
[init_split_files:971] added file: /mnt/9C908FFC908FDB62/Arely/Metatranscriptoma_BP8/Sortmerna_Filter_cdefault/2_MT_BP8/DR04_R1/readb/fwd_0.fq.gz
[init_split_files:971] added file: /mnt/9C908FFC908FDB62/Arely/Metatranscriptoma_BP8/Sortmerna_Filter_cdefault/2_MT_BP8/DR04_R1/readb/fwd_1.fq.gz
[init_split_files:971] added file: /mnt/9C908FFC908FDB62/Arely/Metatranscriptoma_BP8/Sortmerna_Filter_cdefault/2_MT_BP8/DR04_R1/readb/fwd_2.fq.gz
[init_split_files:971] added file: /mnt/9C908FFC908FDB62/Arely/Metatranscriptoma_BP8/Sortmerna_Filter_cdefault/2_MT_BP8/DR04_R1/readb/fwd_3.fq.gz
[init_split_files:971] added file: /mnt/9C908FFC908FDB62/Arely/Metatranscriptoma_BP8/Sortmerna_Filter_cdefault/2_MT_BP8/DR04_R1/readb/fwd_4.fq.gz
[init_split_files:971] added file: /mnt/9C908FFC908FDB62/Arely/Metatranscriptoma_BP8/Sortmerna_Filter_cdefault/2_MT_BP8/DR04_R1/readb/fwd_5.fq.gz
[init_split_files:971] added file: /mnt/9C908FFC908FDB62/Arely/Metatranscriptoma_BP8/Sortmerna_Filter_cdefault/2_MT_BP8/DR04_R1/readb/fwd_6.fq.gz
[init_split_files:971] added file: /mnt/9C908FFC908FDB62/Arely/Metatranscriptoma_BP8/Sortmerna_Filter_cdefault/2_MT_BP8/DR04_R1/readb/fwd_7.fq.gz
[init_split_files:971] added file: /mnt/9C908FFC908FDB62/Arely/Metatranscriptoma_BP8/Sortmerna_Filter_cdefault/2_MT_BP8/DR04_R1/readb/fwd_8.fq.gz
[init_split_files:971] added file: /mnt/9C908FFC908FDB62/Arely/Metatranscriptoma_BP8/Sortmerna_Filter_cdefault/2_MT_BP8/DR04_R1/readb/fwd_9.fq.gz
[init_split_files:971] added file: /mnt/9C908FFC908FDB62/Arely/Metatranscriptoma_BP8/Sortmerna_Filter_cdefault/2_MT_BP8/DR04_R1/readb/fwd_10.fq.gz
[init_split_files:971] added file: /mnt/9C908FFC908FDB62/Arely/Metatranscriptoma_BP8/Sortmerna_Filter_cdefault/2_MT_BP8/DR04_R1/readb/fwd_11.fq.gz
[init_split_files:971] added file: /mnt/9C908FFC908FDB62/Arely/Metatranscriptoma_BP8/Sortmerna_Filter_cdefault/2_MT_BP8/DR04_R1/readb/fwd_12.fq.gz
[init_split_files:971] added file: /mnt/9C908FFC908FDB62/Arely/Metatranscriptoma_BP8/Sortmerna_Filter_cdefault/2_MT_BP8/DR04_R1/readb/fwd_13.fq.gz
[init_split_files:971] added file: /mnt/9C908FFC908FDB62/Arely/Metatranscriptoma_BP8/Sortmerna_Filter_cdefault/2_MT_BP8/DR04_R1/readb/fwd_14.fq.gz
[init_split_files:971] added file: /mnt/9C908FFC908FDB62/Arely/Metatranscriptoma_BP8/Sortmerna_Filter_cdefault/2_MT_BP8/DR04_R1/readb/fwd_15.fq.gz
[split:583] start splitting. Using number of splits equals number of processing threads: 16
[next:311] EOF FWD reached. Total reads: 3116831
[split:694] Done splitting. Reads count: 3116831 Runtime sec: 115.724

[init:135] Readfeed init done in sec [124.742]
[store_to_db:292] Stored Reads statistics to DB:
     all_reads_count= 3116831 all_reads_len= 426288369 min_read_len= 150 max_read_len= 50 total_aligned= 0 total_aligned_id= 0 total_aligned_cov= 0 total_aligned_id_cov= 0 total_denovo= 0 num_short= 0 reads_matched_per_db= TODO is_stats_calc= 0 is_total_reads_mapped_cov= 0

[align:143] ==== Starting alignment ====
[align:146] Number of cores: 16
[align:163] Using number of Processor threads: 16
[Refstats:60] Index Statistics calculation starts ... done in: 0.303241 sec
[align:185] Loading index: 0 part: 1/1 Memory KB: 8 ... 
[align:190] done in [3.36432] sec Memory KB: 3189
[align:193] Loading references ...
[align:197] done in [0.274715] sec. Memory KB: 3343
[align2:70] Processor 0 thread 140470311180032 started
[align2:70] Processor 1 thread 140470319572736 started
[align2:70] Processor 2 thread 140470764156672 started
[align2:70] Processor 3 thread 140470327965440 started
[align2:70] Processor 4 thread 140470286001920 started
[align2:70] Processor 8 thread 140469514266368 started
[align2:70] Processor 6 thread 140469599053568 started
[align2:70] Processor 7 thread 140469522659072 started
[align2:70] Processor 5 thread 140470277609216 started
[align2:70] Processor 9 thread 140469505873664 started
[align2:70] Processor 10 thread 140469497480960 started
[align2:70] Processor 11 thread 140469489088256 started
[align2:70] Processor 12 thread 140469480695552 started
[align2:70] Processor 13 thread 140469472302848 started
[align2:70] Processor 14 thread 140468985788160 started
[align2:70] Processor 15 thread 140468977395456 started
[next:433] EOF FWD reached. Total reads: 194802
[align2:133] Processor 0 thread 140470311180032 done. Processed 194802 reads. Skipped already processed: 0 reads Aligned reads (passing E-value): 126329 Runtime sec: 202.483
[next:433] EOF FWD reached. Total reads: 194802
[align2:133] Processor 8 thread 140469514266368 done. Processed 194802 reads. Skipped already processed: 0 reads Aligned reads (passing E-value): 131663 Runtime sec: 207.415
[next:433] EOF REV reached. Total reads: 194802
[align2:133] Processor 7 thread 140469522659072 done. Processed 194802 reads. Skipped already processed: 0 reads Aligned reads (passing E-value): 137810 Runtime sec: 209.606
[next:433] EOF FWD reached. Total reads: 194802
[align2:133] Processor 2 thread 140470764156672 done. Processed 194802 reads. Skipped already processed: 0 reads Aligned reads (passing E-value): 131767 Runtime sec: 209.773
[next:433] EOF FWD reached. Total reads: 194802
[align2:133] Processor 10 thread 140469497480960 done. Processed 194802 reads. Skipped already processed: 0 reads Aligned reads (passing E-value): 133707 Runtime sec: 211.357
[next:433] EOF REV reached. Total reads: 194802
[align2:133] Processor 1 thread 140470319572736 done. Processed 194802 reads. Skipped already processed: 0 reads Aligned reads (passing E-value): 140061 Runtime sec: 213.255
[next:433] EOF REV reached. Total reads: 194802
[align2:133] Processor 3 thread 140470327965440 done. Processed 194802 reads. Skipped already processed: 0 reads Aligned reads (passing E-value): 139597 Runtime sec: 213.706
[next:433] EOF REV reached. Total reads: 194802
[align2:133] Processor 9 thread 140469505873664 done. Processed 194802 reads. Skipped already processed: 0 reads Aligned reads (passing E-value): 141498 Runtime sec: 214.6
[next:433] EOF REV reached. Total reads: 194801
[align2:133] Processor 15 thread 140468977395456 done. Processed 194801 reads. Skipped already processed: 0 reads Aligned reads (passing E-value): 142875 Runtime sec: 214.676
[next:433] EOF FWD reached. Total reads: 194802
[align2:133] Processor 4 thread 140470286001920 done. Processed 194802 reads. Skipped already processed: 0 reads Aligned reads (passing E-value): 140463 Runtime sec: 217.798
[next:433] EOF FWD reached. Total reads: 194802
[align2:133] Processor 12 thread 140469480695552 done. Processed 194802 reads. Skipped already processed: 0 reads Aligned reads (passing E-value): 144223 Runtime sec: 217.824
[next:433] EOF REV reached. Total reads: 194802
[align2:133] Processor 11 thread 140469489088256 done. Processed 194802 reads. Skipped already processed: 0 reads Aligned reads (passing E-value): 146026 Runtime sec: 219.8
[next:433] EOF REV reached. Total reads: 194802
[align2:133] Processor 5 thread 140470277609216 done. Processed 194802 reads. Skipped already processed: 0 reads Aligned reads (passing E-value): 147927 Runtime sec: 220.329
[next:433] EOF REV reached. Total reads: 194802
[align2:133] Processor 13 thread 140469472302848 done. Processed 194802 reads. Skipped already processed: 0 reads Aligned reads (passing E-value): 146256 Runtime sec: 220.358
[next:433] EOF FWD reached. Total reads: 194802
[align2:133] Processor 6 thread 140469599053568 done. Processed 194802 reads. Skipped already processed: 0 reads Aligned reads (passing E-value): 143398 Runtime sec: 220.649
[next:433] EOF FWD reached. Total reads: 194802
[align2:133] Processor 14 thread 140468985788160 done. Processed 194802 reads. Skipped already processed: 0 reads Aligned reads (passing E-value): 146851 Runtime sec: 221.244
[align:220] done index: 0 part: 1 in 221.245 sec Memory KB: 4836
[align:227] Index and References unloaded in 0.787236 sec. Memory KB: 4836
[align:237] ==== Done alignment in 225.672 sec ====

[store_to_db:292] Stored Reads statistics to DB:
     all_reads_count= 3116831 all_reads_len= 426288369 min_read_len= 150 max_read_len= 50 total_aligned= 2240451 total_aligned_id= 0 total_aligned_cov= 0 total_aligned_id_cov= 0 total_denovo= 0 num_short= 0 reads_matched_per_db= TODO is_stats_calc= 0 is_total_reads_mapped_cov= 0

[writeSummary:179] ==== Starting summary of alignment statistics ====
[Refstats:60] Index Statistics calculation starts ... done in: 0.297006 sec
[write:62] Using summary file: unpaired_DR04_3d_R1_2_ribosomal.log
[writeSummary:185] ==== Done summary in sec [0.297355] ====

[writeReports:160] === Report generation starts ===
[writeReports:175] Restored Readstats from DB: 1
[Refstats:60] Index Statistics calculation starts ... done in: 0.290064 sec
[validate_out_type:139] Output type: 
1-file  2-files  paired  paired_in  paired_out  out2  sout  other  otype
   +                                                           +     1
[set_num_out:162] num_out: 1
[init:60] num_out: 1
[validate_out_type:139] Output type: 
1-file  2-files  paired  paired_in  paired_out  out2  sout  other  otype
   +                                                           +     1
[set_num_out:162] num_out: 1
[init:60] num_out: 1
[writeReports:190] loading reference 0 part 1/1 ... done in 0.251523 sec
[report:93] Report Processor: 0 thread: 140468977395456 started. Memory KB: 4666
[report:93] Report Processor: 2 thread: 140469472302848 started. Memory KB: 4666
[report:93] Report Processor: 3 thread: 140469480695552 started. Memory KB: 4666
[report:93] Report Processor: 1 thread: 140468985788160 started. Memory KB: 4666
[report:93] Report Processor: 4 thread: 140470764156672 started. Memory KB: 4666
[report:93] Report Processor: 8 thread: 140470319572736 started. Memory KB: 4666
[report:93] Report Processor: 5 thread: 140470755763968 started. Memory KB: 4666
[report:93] Report Processor: 7 thread: 140470327965440 started. Memory KB: 4666
[report:93] Report Processor: 9 thread: 140470311180032 started. Memory KB: 4666
[report:93] Report Processor: 6 thread: 140470747371264 started. Memory KB: 4666
[report:93] Report Processor: 11 thread: 140470277609216 started. Memory KB: 4666
[report:93] Report Processor: 10 thread: 140470286001920 started. Memory KB: 4666
[report:93] Report Processor: 12 thread: 140469599053568 started. Memory KB: 4666
[report:93] Report Processor: 13 thread: 140469522659072 started. Memory KB: 4666
[report:93] Report Processor: 14 thread: 140469514266368 started. Memory KB: 4666
[report:93] Report Processor: 15 thread: 140469505873664 started. Memory KB: 4666
Violación de segmento (`core' generado)

**using v4.3.2 threads default**

arely@proyecto-h:/mnt/9C908FFC908FDB62/Arely/Metatranscriptoma_BP8/Sortmerna_Filter_cdefault/2_MT_BP8$ /home/proyectoh/Programas/sortmerna-4.3.2-Linux/bin/sortmerna -ref /home/proyectoh/Programas/sortmerna-4.3.2-Linux/database/smr_v4.3_default_db.fasta -reads /mnt/9C908FFC908FDB62/Arely/Metatranscriptoma_BP8/Trimmomatic_Filter_cutdefault/unpaired_DR04_R1_2.fastq.gz -fastx -other unpaired_DR04_3d_R1_non-ribosomal_2 -aligned unpaired_DR04_3d_R1_2_ribosomal --workdir /mnt/9C908FFC908FDB62/Arely/Metatranscriptoma_BP8/Sortmerna_Filter_cdefault/2_MT_BP8/DR04_R1/ --idx-dir /mnt/9C908FFC908FDB62/Arely/MT_BP8/SortMeRNA_Filter/idx/ 
[process:1372] === Options processing starts ... ===
Found value: /home/proyectoh/Programas/sortmerna-4.3.2-Linux/bin/sortmerna
Found flag: -ref
Found value: /home/proyectoh/Programas/sortmerna-4.3.2-Linux/database/smr_v4.3_default_db.fasta of previous flag: -ref
Found flag: -reads
Found value: /mnt/9C908FFC908FDB62/Arely/Metatranscriptoma_BP8/Trimmomatic_Filter_cutdefault/unpaired_DR04_R1_2.fastq.gz of previous flag: -reads
Found flag: -fastx
Previous flag: -fastx is Boolean. Setting to True
Found flag: -other
Found value: unpaired_DR04_3d_R1_non-ribosomal_2 of previous flag: -other
Found flag: -aligned
Found value: unpaired_DR04_3d_R1_2_ribosomal of previous flag: -aligned
Found flag: --workdir
Found value: /mnt/9C908FFC908FDB62/Arely/Metatranscriptoma_BP8/Sortmerna_Filter_cdefault/2_MT_BP8/DR04_R1/ of previous flag: --workdir
Found flag: --idx-dir
Found value: /mnt/9C908FFC908FDB62/Arely/MT_BP8/SortMeRNA_Filter/idx/ of previous flag: --idx-dir
[opt_workdir:990] Using WORKDIR: "/mnt/9C908FFC908FDB62/Arely/Metatranscriptoma_BP8/Sortmerna_Filter_cdefault/2_MT_BP8/DR04_R1/" as specified
[process:1456] Processing option: aligned with value: unpaired_DR04_3d_R1_2_ribosomal
[process:1456] Processing option: fastx with value: 
[process:1456] Processing option: idx-dir with value: /mnt/9C908FFC908FDB62/Arely/MT_BP8/SortMeRNA_Filter/idx/
[opt_idxdir:1014] Using IDX dir: ["/mnt/9C908FFC908FDB62/Arely/MT_BP8/SortMeRNA_Filter/idx/" as specified
[process:1456] Processing option: other with value: unpaired_DR04_3d_R1_non-ribosomal_2
[process:1456] Processing option: reads with value: /mnt/9C908FFC908FDB62/Arely/Metatranscriptoma_BP8/Trimmomatic_Filter_cutdefault/unpaired_DR04_R1_2.fastq.gz
[opt_reads:97] Processing reads file [1] out of total [1] files
[process:1456] Processing option: ref with value: /home/proyectoh/Programas/sortmerna-4.3.2-Linux/database/smr_v4.3_default_db.fasta
[opt_ref:157] Processing reference [1] out of total [1] references
[opt_ref:205] File "/home/proyectoh/Programas/sortmerna-4.3.2-Linux/database/smr_v4.3_default_db.fasta" exists and is readable
[process:1476] === Options processing done ===
[process:1477] Alignment type: [best:1 num_alignments:1 min_lis:2 seeds:2]
[validate_kvdbdir:1223] Key-value DB location "/mnt/9C908FFC908FDB62/Arely/Metatranscriptoma_BP8/Sortmerna_Filter_cdefault/2_MT_BP8/DR04_R1/kvdb"
[validate_kvdbdir:1259] Creating KVDB directory: "/mnt/9C908FFC908FDB62/Arely/Metatranscriptoma_BP8/Sortmerna_Filter_cdefault/2_MT_BP8/DR04_R1/kvdb"
[validate_idxdir:1189] Using index directory: "/mnt/9C908FFC908FDB62/Arely/MT_BP8/SortMeRNA_Filter/idx/"
[validate_idxdir:1205] IDX directory: "/mnt/9C908FFC908FDB62/Arely/MT_BP8/SortMeRNA_Filter/idx/" exists and is not empty
[validate_readb_dir:1281] Using split reads directory : "/mnt/9C908FFC908FDB62/Arely/Metatranscriptoma_BP8/Sortmerna_Filter_cdefault/2_MT_BP8/DR04_R1/readb"
[validate_readb_dir:1289] Created split reads directory - OK
[main:62] Running command:
/home/proyectoh/Programas/sortmerna-4.3.2-Linux/bin/sortmerna -ref /home/proyectoh/Programas/sortmerna-4.3.2-Linux/database/smr_v4.3_default_db.fasta -reads /mnt/9C908FFC908FDB62/Arely/Metatranscriptoma_BP8/Trimmomatic_Filter_cutdefault/unpaired_DR04_R1_2.fastq.gz -fastx -other unpaired_DR04_3d_R1_non-ribosomal_2 -aligned unpaired_DR04_3d_R1_2_ribosomal --workdir /mnt/9C908FFC908FDB62/Arely/Metatranscriptoma_BP8/Sortmerna_Filter_cdefault/2_MT_BP8/DR04_R1/ --idx-dir /mnt/9C908FFC908FDB62/Arely/MT_BP8/SortMeRNA_Filter/idx/ 
[Index:102] Found 4 non-empty index files. Skipping indexing.
[init:108] Readfeed init started
[define_format:885] file: "/mnt/9C908FFC908FDB62/Arely/Metatranscriptoma_BP8/Trimmomatic_Filter_cutdefault/unpaired_DR04_R1_2.fastq.gz" is FASTQ gzipped
[count_reads:919] started count  ...   
[next:311] EOF FWD reached. Total reads: 3116831
[count_reads:949] done count. Elapsed time: 8.92129 sec. Total reads: 3116831
[init_split_files:971] added file: /mnt/9C908FFC908FDB62/Arely/Metatranscriptoma_BP8/Sortmerna_Filter_cdefault/2_MT_BP8/DR04_R1/readb/fwd_0.fq.gz
[init_split_files:971] added file: /mnt/9C908FFC908FDB62/Arely/Metatranscriptoma_BP8/Sortmerna_Filter_cdefault/2_MT_BP8/DR04_R1/readb/fwd_1.fq.gz
[split:583] start splitting. Using number of splits equals number of processing threads: 2
[next:311] EOF FWD reached. Total reads: 3116831
[split:694] Done splitting. Reads count: 3116831 Runtime sec: 115.272

[init:135] Readfeed init done in sec [124.195]
[store_to_db:292] Stored Reads statistics to DB:
     all_reads_count= 3116831 all_reads_len= 426288369 min_read_len= 150 max_read_len= 50 total_aligned= 0 total_aligned_id= 0 total_aligned_cov= 0 total_aligned_id_cov= 0 total_denovo= 0 num_short= 0 reads_matched_per_db= TODO is_stats_calc= 0 is_total_reads_mapped_cov= 0

[align:143] ==== Starting alignment ====
[align:146] Number of cores: 16
[align:163] Using number of Processor threads: 2
[Refstats:60] Index Statistics calculation starts ... done in: 0.295129 sec
[align:185] Loading index: 0 part: 1/1 Memory KB: 7 ... 
[align:190] done in [3.33311] sec Memory KB: 3187
[align:193] Loading references ...
[align:197] done in [0.274642] sec. Memory KB: 3341
[align2:70] Processor 0 thread 139688870389504 started
[align2:70] Processor 1 thread 139688878782208 started
[next:433] EOF FWD reached. Total reads: 1558416
[align2:133] Processor 0 thread 139688870389504 done. Processed 1558416 reads. Skipped already processed: 0 reads Aligned reads (passing E-value): 1107352 Runtime sec: 967.156
[next:433] EOF REV reached. Total reads: 1558415
[align2:133] Processor 1 thread 139688878782208 done. Processed 1558415 reads. Skipped already processed: 0 reads Aligned reads (passing E-value): 1133099 Runtime sec: 983.088
[align:220] done index: 0 part: 1 in 983.088 sec Memory KB: 4781
[align:227] Index and References unloaded in 0.797774 sec. Memory KB: 4781
[align:237] ==== Done alignment in 987.494 sec ====

[store_to_db:292] Stored Reads statistics to DB:
     all_reads_count= 3116831 all_reads_len= 426288369 min_read_len= 150 max_read_len= 50 total_aligned= 2240451 total_aligned_id= 0 total_aligned_cov= 0 total_aligned_id_cov= 0 total_denovo= 0 num_short= 0 reads_matched_per_db= TODO is_stats_calc= 0 is_total_reads_mapped_cov= 0

[writeSummary:179] ==== Starting summary of alignment statistics ====
[Refstats:60] Index Statistics calculation starts ... done in: 0.380085 sec
[write:62] Using summary file: unpaired_DR04_3d_R1_2_ribosomal.log
[writeSummary:185] ==== Done summary in sec [0.380297] ====

[writeReports:160] === Report generation starts ===
[writeReports:175] Restored Readstats from DB: 1
[Refstats:60] Index Statistics calculation starts ... done in: 0.299592 sec
[validate_out_type:139] Output type: 
1-file  2-files  paired  paired_in  paired_out  out2  sout  other  otype
   +                                                           +     1
[set_num_out:162] num_out: 1
[init:60] num_out: 1
[validate_out_type:139] Output type: 
1-file  2-files  paired  paired_in  paired_out  out2  sout  other  otype
   +                                                           +     1
[set_num_out:162] num_out: 1
[init:60] num_out: 1
[writeReports:190] loading reference 0 part 1/1 ... done in 0.273974 sec
[report:93] Report Processor: 0 thread: 139688878782208 started. Memory KB: 2159
[report:93] Report Processor: 1 thread: 139688870389504 started. Memory KB: 2159
Violación de segmento (`core' generado)

**Comment by biocodz** [comment]
thanks for the feedback! I'm looking into it. If it's a bug, it should not take long to fix. Meanwhile I still recommend to switch to 4.3.4

**Comment by biocodz** [comment]
Using 4.3.4 was not able to reproduce your problem. I have created a new test and the results look like (tested on Windows but never mind)
```
python scripts/run.py -n t46
Current dir: C:/Users/biocodz\a01_code\sortmerna\scripts
[run.py:__main__] Using Environment configuration file: C:/Users/biocodz\a01_code\sortmerna\scripts\env.jinja.yaml
[run.py:__main__] Using Build configuration template: C:/Users/biocodz\a01_code\sortmerna\scripts\test.jinja.yaml
[run.py:__main__] --envn was not specified - using WIN
[run.py:__main__] using C:/Users/biocodz/a01_code/sortmerna/dist/t1/release\bin\sortmerna.exe
[process_smr_opts] '-workdir' option was provided. Using workdir: [C:/Users/biocodz\sortmerna\run]
[process_smr_opts] '-workdir' option was provided. Using workdir: [C:/Users/biocodz\sortmerna\run]
[run.py:__main__] Removing KVDB dir: C:/Users/biocodz/sortmerna/run\kvdb
[run.py:__main__] Removing Aligned Output: C:/Users/biocodz/sortmerna/run\out
[run.py:__main__] Running t46: segfault - iss 288-2
[run] Running: C:/Users/biocodz/a01_code/sortmerna/dist/t1/release\bin\sortmerna.exe -ref C:/Users/biocodz/a01_code/sortmerna/data/rRNA_databases/smr_v4.3_default_db.fasta -reads C:/Users/biocodz/a01_data/bio/reads/rna/DRR121111_5k.fastq.gz -fastx -other -num_alignments 1 -v -dbg-level 2 -threads 8 -index 2 -task 4 -workdir C:/Users/biocodz/sortmerna/run in C:/Users/biocodz/a01_code/sortmerna
...
...
[validate_out_type:139] Output type:
1-file  2-files  paired  paired_in  paired_out  out2  sout  other  otype
   +                                                           +     1
[set_num_out:162] num_out: 1
[init:60] num_out: 1
[openfw:108] Opened output file C:/Users/biocodz/sortmerna/run\out\aligned_0.fq.gz for writing.
[openfw:108] Opened output file C:/Users/biocodz/sortmerna/run\out\aligned_1.fq.gz for writing.
[openfw:108] Opened output file C:/Users/biocodz/sortmerna/run\out\aligned_2.fq.gz for writing.
[openfw:108] Opened output file C:/Users/biocodz/sortmerna/run\out\aligned_3.fq.gz for writing.
[openfw:108] Opened output file C:/Users/biocodz/sortmerna/run\out\aligned_4.fq.gz for writing.
[openfw:108] Opened output file C:/Users/biocodz/sortmerna/run\out\aligned_5.fq.gz for writing.
[openfw:108] Opened output file C:/Users/biocodz/sortmerna/run\out\aligned_6.fq.gz for writing.
[openfw:108] Opened output file C:/Users/biocodz/sortmerna/run\out\aligned_7.fq.gz for writing.
[validate_out_type:139] Output type:
1-file  2-files  paired  paired_in  paired_out  out2  sout  other  otype
   +                                                           +     1
[set_num_out:162] num_out: 1
...
...
[strip_path_sfx:169] moving C:/Users/biocodz/sortmerna/run\out\other_0.fq.gz -> "C:/Users/biocodz/sortmerna/run/out/other.fq.gz"
[writeReports:268] === done Reports in 2.32984 sec ===

[run] Run time: 34.389060974121094
[process_output] aligned.log
[validate_log] testing num_reads: 10000 Expected: 10000
[validate_log] testing num_hits: 9847 Expected: 9847
[validate_log] testing num_fail: 153 Expected: 153
[process_output] aligned.fq.gz
[process_output] Testing count of reads in aligned.fq.gz: 9847 Expected: 9847
[process_output] other.fq.gz
[process_output] Testing count of reads in other.fq.gz: 153 Expected: 153
```

**Comment by AryLech** [comment]
thanks for your answer.

Effectively, using v4.3.4 and removing -paired_out (that´s solved the problem in v4.3.2) the program run properly. I think the option -paired_out was causing the error when I used previosly v4.3.4

**Comment by biocodz** [comment]
Tried the same test with `paired_out` and it still ran OK
```
  python /media/sf_a01_code/sortmerna/scripts/run.py -e LNX_VBox_Ubuntu_1604 -n t46
Current dir: /media/sf_a01_code/sortmerna/scripts
[run.py:__main__] Using Environment configuration file: /media/sf_a01_code/sortmerna/scripts/env.jinja.yaml
[run.py:__main__] Using Build configuration template: /media/sf_a01_code/sortmerna/scripts/test.jinja.yaml
[run.py:__main__] using /home/biocodz/sortmerna/dist/bin/sortmerna
[process_smr_opts] '-workdir' option was provided. Using workdir: [/home/biocodz/sortmerna/run]
[process_smr_opts] '-workdir' option was provided. Using workdir: [/home/biocodz/sortmerna/run]
[run.py:__main__] Removing KVDB dir: /home/biocodz/sortmerna/run/kvdb
[run.py:__main__] Removing Aligned Output: /home/biocodz/sortmerna/run/out
[run.py:__main__] Running t46: segfault - iss 288-2
[run] Running: /home/biocodz/sortmerna/dist/bin/sortmerna -ref /media/sf_a01_code/sortmerna/data/rRNA_databases/smr_v4.3_default_db.fasta -reads /media/sf_a01_data/bio/reads/rna/DRR121111_5k_paired.fastq.gz -fastx -other -paired_out -num_alignments 1 -v -dbg-level 2 -threads 8 -index 2 -task 4 -workdir /home/biocodz/sortmerna/run in /media/sf_a01_code/sortmerna
[process:1376] === Options processing starts ... ===
Found value: /home/biocodz/sortmerna/dist/bin/sortmerna
...
[split:717] Done splitting. Reads count: 10000 Runtime sec: 1.01962

[init:135] Readfeed init done in sec [1.14629]
[store_to_db:292] Stored Reads statistics to DB:
     all_reads_count= 10000 all_reads_len= 3010000 min_read_len= 301 max_read_len= 301 total_aligned= 0 total_aligned_id= 0 total_aligned_cov= 0 total_aligned_id_cov= 0 total_denovo= 0 num_short= 0 reads_matched_per_db= TODO is_stats_calc= 0 is_total_reads_mapped_cov= 0

[align:143] ==== Starting alignment ====
[align:146] Number of cores: 8
..
...
[align:227] Index and References unloaded in 1.051 sec. Memory KB: 3374
[align:237] ==== Done alignment in 44.7842 sec ====
...
...
[writeReports:169] === Report generation starts ===
[writeReports:184] Restored Readstats from DB: 1
[Refstats:60] Index Statistics calculation starts ... done in: 0.606508 sec
[validate_out_type:139] Output type:
1-file  2-files  paired  paired_in  paired_out  out2  sout  other  otype
   +                +                  +                       +     15
[set_num_out:162] num_out: 1
...
...
[strip_path_sfx:169] moving /home/biocodz/sortmerna/run/out/other_0.fq.gz -> "/home/biocodz/sortmerna/run/out/other.fq.gz"
[writeReports:268] === done Reports in 2.66259 sec ===

[run] Run time: 50.48587369918823
[process_output] aligned.log
[validate_log] testing num_reads: 10000 Expected: 10000
[validate_log] testing num_hits: 9847 Expected: 9847
[validate_log] testing num_fail: 153 Expected: 153
```
So, something else must have caused your problem.

Thank you for the input. 
Please, don't hesitate to report any problems. Some bugs are still lurking somewhere in the code for sure .

**Comment by AryLech** [comment]
Effectively, something else must have caused my problem.

I rerun all my samples from the beginning and the error doesn't appear more

thanks

**Comment by AlexUmbach** [comment]
Hello! 

I hate to reopen this, but I'm encountering a similar segmentation fault issue when processing paired-end reads. I've tried reverting to v4.3.4 from v4.3.6, and still it persists.

```
(metaomics) aumbach@mellea:/Analysis/aumbach/PhD/transcriptomics/RBC_RNA_transcriptomics/sortmerna$ sortmerna --ref ref_db/silva-bac-16s-id90.fasta --reads ../quality_filtering/trimmed_data/NexD1_9_A_S25_L001_R1_001.fastq --reads ../quality_filtering/trimmed_data/NexD1_9_A_S25_L001_R2_001.fastq
[process:1376] === Options processing starts ... ===
Found value: sortmerna
Found flag: --ref
Found value: ref_db/silva-bac-16s-id90.fasta of previous flag: --ref
Found flag: --reads
Found value: ../quality_filtering/trimmed_data/NexD1_9_A_S25_L001_R1_001.fastq of previous flag: --reads
Found flag: --reads
Found value: ../quality_filtering/trimmed_data/NexD1_9_A_S25_L001_R2_001.fastq of previous flag: --reads
[process:1460] Processing option: reads with value: ../quality_filtering/trimmed_data/NexD1_9_A_S25_L001_R1_001.fastq
[opt_reads:97] Processing reads file [1] out of total [2] files
[process:1460] Processing option: reads with value: ../quality_filtering/trimmed_data/NexD1_9_A_S25_L001_R2_001.fastq
[opt_reads:97] Processing reads file [2] out of total [2] files
[process:1460] Processing option: ref with value: ref_db/silva-bac-16s-id90.fasta
[opt_ref:157] Processing reference [1] out of total [1] references
[opt_ref:205] File "/Analysis/aumbach/PhD/transcriptomics/RBC_RNA_transcriptomics/sortmerna/ref_db/silva-bac-16s-id90.fasta" exists and is readable
[process:1480] === Options processing done ===
[process:1481] Alignment type: [best:1 num_alignments:1 min_lis:2 seeds:2]
[validate_kvdbdir:1221] 'workdir' option was not provided. Using USERDIR to set the working directory: ""
[validate_kvdbdir:1227] Key-value DB location "/home/aumbach/sortmerna/run/kvdb"
[validate_kvdbdir:1263] Creating KVDB directory: "/home/aumbach/sortmerna/run/kvdb"
[validate_idxdir:1193] Using index directory: "/home/aumbach/sortmerna/run/idx"
[validate_idxdir:1201] Created index directory - OK
[validate_readb_dir:1285] Using split reads directory : "/home/aumbach/sortmerna/run/readb"
[validate_readb_dir:1293] Created split reads directory - OK
[validate_aligned_pfx:1314] Checking output directory: "/home/aumbach/sortmerna/run/out"
[validate:1508] No output format has been chosen (fastx|sam|blast|otu_map). Using default 'blast'
[main:62] Running command:
sortmerna --ref ref_db/silva-bac-16s-id90.fasta --reads ../quality_filtering/trimmed_data/NexD1_9_A_S25_L001_R1_001.fastq --reads ../quality_filtering/trimmed_data/NexD1_9_A_S25_L001_R2_001.fastq
[build_index:1127] ==== Index building started ====
[build_index:1190] Begin indexing file ref_db/silva-bac-16s-id90.fasta of size: 19437013 under index name /home/aumbach/sortmerna/run/idx/15734375058464002811
  done.

 [build_index:2108] ==== Done index building in 77.5257 sec ====

[init:108] Readfeed init started
[define_format:915] file: "../quality_filtering/trimmed_data/NexD1_9_A_S25_L001_R1_001.fastq" is FASTQ flat ASCII
[define_format:915] file: "../quality_filtering/trimmed_data/NexD1_9_A_S25_L001_R2_001.fastq" is FASTQ flat ASCII
[count_reads:949] started count  ...
^[[A^[[B[next:322] EOF REV reached. Total reads: 64517482
[count_reads:979] done count. Elapsed time: 263.648 sec. Total reads: 129034965
[init_split_files:1001] added file: /home/aumbach/sortmerna/run/readb/fwd_0.fq
[init_split_files:1001] added file: /home/aumbach/sortmerna/run/readb/rev_0.fq
[init_split_files:1001] added file: /home/aumbach/sortmerna/run/readb/fwd_1.fq
[init_split_files:1001] added file: /home/aumbach/sortmerna/run/readb/rev_1.fq
[split:605] start splitting. Using number of splits equals number of processing threads: 2
^[[A^[[A^[[A[next:322] EOF REV reached. Total reads: 64517482
Segmentation fault (core dumped)
```

```
Linux mellea 5.15.0-78-generic #85-Ubuntu SMP Fri Jul 7 15:25:09 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
``` 

I've tried a combination of output options that were detailed in previous posts/comments, including -fastx -other -paired_out -paired_in. Unlike the previous comments, I've never been able to run sortmerna _without_ a segmentation fault. 

Any help would be great!

**Comment by biocodz** [comment]
I would not advise to revert from 4.3.6 to 4.3.4. Your problem is most likely caused by the resource allocation like directory and memory limits. Similar problems were reported on a few occasions: [Resource allocation problems](https://github.com/sortmerna/sortmerna/issues?q=is%3Aissue+resource)

**Comment by caizhangbin** [comment]
Hi, I am using sortmerna/4.3.6 but I keep getting this  segmentation fault if I used --fastx --other option:
#SBATCH --mem-per-cpu=375G
/localscratch/spool/slurmd/job44815350/slurm_script: line 33: 154306 Segmentation fault      (core dumped) sortmerna --threads 300 --workdir /sortmerna/D73PD --ref "$ref4" --ref "$ref5" --ref "$ref6" --ref "$ref7" --ref "$ref8" --ref "$ref9" --ref "$ref10" --ref "$ref11" --reads NS.2174.003.UDP0038_i7---UDP0038_i5.D73PD_R1.fastq.gz --reads NS.2174.003.UDP0038_i7---UDP0038_i5.D73PD_R2.fastq.gz --fastx --other
any suggestions?

**Comment by biocodz** [comment]
could you, please, create a separate issue for this, and provide the [trace](https://github.com/sortmerna/sortmerna?tab=readme-ov-file#execution-trace) (if there is any)
